[WIP] Add alert in settings page for instance in multiple groups of instances
dalibo/temboard pull request #1287
Opened 2023-10-25 08:53 UTC by MarionGiusti

2023-10-25 09:08 UTC, bersace requested changes

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +  <modal-dialog id="modalMigrationGroups" title="Warning">
title="Instance in multiple groups"

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +        <b>This instance is in more than one group of instances.</b><br>
Éviter `<br/>`. N'utiliser que `<p>`.

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +      <p v-if="migration_groups === 'instance_groups'" class="alert alert-info">
je suis pour laisser le style normal. supprimer `class`.

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +      migration_groups: "",
bonne idée.
j'appellerai cette propriété `object_class` avec comme valeurs possible `instance` ou `instance_group`.

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +/* A Bootstrap dialog with two steps: discover and register.
oups ^^

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +<script type="text/javascript">
j'appelerai le widget `EnvironmentMigrationDialog`.

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/static/src/components/settings/MigrationGroupsWizard.vue
> +        Please report feedback on GitHub issue <a href="https://github.com/dalibo/temboard/issues/1283">#XXX</a>. <br>
Remplacer XXX par 1283.

2023-10-25 09:08 UTC, bersace commented on ui/temboardui/templates/settings/instance.html
> +              <i class="fa fa-warning"></i>
- Supprimer le bouton.
- Mettre directement `v-on:click=` sur `<i>`.
- Ajouter `text-warning` à `<i class=>`.
- Ajouter `style="cursor: pointer;` à `<i>`.
- Ajouter `title="Instance in multiple groups. Click for details."`

2023-10-26 13:58 UTC, pgiraud commented on ui/temboardui/static/src/components/settings/EnvironmentMigrationDialog.vue
> +<script type="text/javascript">
I suggest we start using the composition API since it's already available in VueJS 2.7.

`<script setup>`

2023-10-26 13:58 UTC, pgiraud commented on ui/temboardui/static/src/components/settings/EnvironmentMigrationDialog.vue
> +        <p><b>This instance is in more than one group of instances.</b></p>
`<p><b>This instance belongs to more than one group of instances.</b></p>`

2023-10-27 07:31 UTC, pgiraud approved these changes

2023-10-27 07:47 UTC, pirlgon approved these changes

2023-10-27 08:25 UTC, merged