Migrate dashboard plugin to flask
dalibo/temboard pull request #1470
Opened 2024-07-30 12:36 UTC by pirlgon

2024-07-30 14:33 UTC, MarionGiusti approved these changes

2024-07-30 15:50 UTC, bersace commented on ui/temboardui/web/flask.py
> +        # Register an unique endpoint name for each proxy.
Excellent commentaire. Le message de commit devient redondant. Pas grave.

2024-07-30 15:51 UTC, bersace commented on ui/temboardui/plugins/dashboard/__init__.py
> -                    r"/js/dashboard/(.*)",
:golfing:

2024-07-30 15:52 UTC, bersace commented on ui/temboardui/plugins/dashboard/__init__.py
>  import logging
Peux-tu créer `dashboard/routes.py` et ne garder que `DashboardPlugin` dans `__init__.py` ? ça fait déjà beaucoup pour un `__init__.py`.

2024-07-31 06:38 UTC, pirlgon commented on ui/temboardui/plugins/dashboard/__init__.py
>  import logging
j'avais loupé que c'était ce que tu as fait pour settings

2024-07-31 07:10 UTC, pirlgon commented on ui/temboardui/web/flask.py
> +        # Register an unique endpoint name for each proxy.
:)

2024-07-31 13:18 UTC, bersace commented on ui/temboardui/web/flask.py
> +            path_segments = request.path.split("/")[4:]
``` python
*_, path = request.split("/", 4)
...
path=f"/{path}
...
```

2024-07-31 13:20 UTC, bersace commented on ui/temboardui/web/routes/dashboard.py
> +import logging
Je pensais plutôt à `temboardui/plugins/dashboard/routes.py`.

2024-07-31 13:21 UTC, bersace commented on ui/temboardui/plugins/dashboard/__init__.py
> +        instance_proxy.generic_proxy("/dashboard")
Ajouter ici `__import__(__name__ + '.routes')`

2024-08-02 06:18 UTC, pgiraud requested changes

2024-08-02 06:18 UTC, pgiraud commented on ui/temboardui/templates/flask/dashboard.html
> +    :discover='{{ discover }}'
Can't we just use `instance.discover`?

2024-08-02 09:41 UTC, pgiraud commented on ui/temboardui/templates/flask/dashboard.html
> +    :discover="{{ instance.discover}}"
:discover="{{ instance.discover }}"

2024-08-02 12:04 UTC, pgiraud commented on ui/temboardui/templates/flask/dashboard.html
> +-->
While we're at it, can we remove this commented code? I'm sure it was added for debug. Let's remove it.

2024-08-02 12:04 UTC, pgiraud approved these changes

2024-08-02 12:28 UTC, merged